/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.zaluum.visa.swig;

public class SWIGTYPE_p_f_unsigned_long_unsigned_long_unsigned_long_p_void__long {
  private long swigCPtr;

  protected SWIGTYPE_p_f_unsigned_long_unsigned_long_unsigned_long_p_void__long(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_unsigned_long_unsigned_long_unsigned_long_p_void__long() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_unsigned_long_unsigned_long_unsigned_long_p_void__long obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

