/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native int viOpenDefaultRM(long jarg1);
  public final static native int viFindRsrc(long jarg1, String jarg2, long jarg3, long jarg4, String jarg5);
  public final static native int viFindNext(long jarg1, String jarg2);
  public final static native int viParseRsrc(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int viParseRsrcEx(long jarg1, String jarg2, long jarg3, long jarg4, String jarg5, String jarg6, String jarg7);
  public final static native int viOpen(long jarg1, String jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viClose(long jarg1);
  public final static native int viSetAttribute(long jarg1, long jarg2, long jarg3);
  public final static native int viGetAttribute(long jarg1, long jarg2, long jarg3);
  public final static native int viStatusDesc(long jarg1, int jarg2, String jarg3);
  public final static native int viTerminate(long jarg1, int jarg2, long jarg3);
  public final static native int viLock(long jarg1, long jarg2, long jarg3, String jarg4, String jarg5);
  public final static native int viUnlock(long jarg1);
  public final static native int viEnableEvent(long jarg1, long jarg2, int jarg3, long jarg4);
  public final static native int viDisableEvent(long jarg1, long jarg2, int jarg3);
  public final static native int viDiscardEvents(long jarg1, long jarg2, int jarg3);
  public final static native int viWaitOnEvent(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viInstallHandler(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viUninstallHandler(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viRead(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viReadAsync(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viReadToFile(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int viWrite(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viWriteAsync(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viWriteFromFile(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int viAssertTrigger(long jarg1, int jarg2);
  public final static native int viReadSTB(long jarg1, long jarg2);
  public final static native int viClear(long jarg1);
  public final static native int viSetBuf(long jarg1, int jarg2, long jarg3);
  public final static native int viFlush(long jarg1, int jarg2);
  public final static native int viBufWrite(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viBufRead(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viPrintf(long jarg1, String jarg2);
  public final static native int viSPrintf(long jarg1, long jarg2, String jarg3);
  public final static native int viScanf(long jarg1, String jarg2);
  public final static native int viSScanf(long jarg1, long jarg2, String jarg3);
  public final static native int viQueryf(long jarg1, String jarg2, String jarg3);
  public final static native int viIn8(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut8(long jarg1, int jarg2, long jarg3, short jarg4);
  public final static native int viIn16(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut16(long jarg1, int jarg2, long jarg3, int jarg4);
  public final static native int viIn32(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut32(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viIn64(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut64(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viIn8Ex(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut8Ex(long jarg1, int jarg2, long jarg3, short jarg4);
  public final static native int viIn16Ex(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut16Ex(long jarg1, int jarg2, long jarg3, int jarg4);
  public final static native int viIn32Ex(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut32Ex(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viIn64Ex(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viOut64Ex(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viMoveIn8(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut8(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveIn16(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut16(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveIn32(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut32(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveIn64(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut64(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveIn8Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut8Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveIn16Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut16Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveIn32Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut32Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveIn64Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMoveOut64Ex(long jarg1, int jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int viMove(long jarg1, int jarg2, long jarg3, int jarg4, int jarg5, long jarg6, int jarg7, long jarg8);
  public final static native int viMoveAsync(long jarg1, int jarg2, long jarg3, int jarg4, int jarg5, long jarg6, int jarg7, long jarg8, long jarg9);
  public final static native int viMoveEx(long jarg1, int jarg2, long jarg3, int jarg4, int jarg5, long jarg6, int jarg7, long jarg8);
  public final static native int viMoveAsyncEx(long jarg1, int jarg2, long jarg3, int jarg4, int jarg5, long jarg6, int jarg7, long jarg8, long jarg9);
  public final static native int viMapAddress(long jarg1, int jarg2, long jarg3, long jarg4, int jarg5, long jarg6, long jarg7);
  public final static native int viUnmapAddress(long jarg1);
  public final static native int viMapAddressEx(long jarg1, int jarg2, long jarg3, long jarg4, int jarg5, long jarg6, long jarg7);
  public final static native void viPeek8(long jarg1, long jarg2, long jarg3);
  public final static native void viPoke8(long jarg1, long jarg2, short jarg3);
  public final static native void viPeek16(long jarg1, long jarg2, long jarg3);
  public final static native void viPoke16(long jarg1, long jarg2, int jarg3);
  public final static native void viPeek32(long jarg1, long jarg2, long jarg3);
  public final static native void viPoke32(long jarg1, long jarg2, long jarg3);
  public final static native void viPeek64(long jarg1, long jarg2, long jarg3);
  public final static native void viPoke64(long jarg1, long jarg2, long jarg3);
  public final static native int viMemAlloc(long jarg1, long jarg2, long jarg3);
  public final static native int viMemFree(long jarg1, long jarg2);
  public final static native int viMemAllocEx(long jarg1, long jarg2, long jarg3);
  public final static native int viMemFreeEx(long jarg1, long jarg2);
  public final static native int viGpibControlREN(long jarg1, int jarg2);
  public final static native int viGpibControlATN(long jarg1, int jarg2);
  public final static native int viGpibSendIFC(long jarg1);
  public final static native int viGpibCommand(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int viGpibPassControl(long jarg1, int jarg2, int jarg3);
  public final static native int viVxiCommandQuery(long jarg1, int jarg2, long jarg3, long jarg4);
  public final static native int viAssertUtilSignal(long jarg1, int jarg2);
  public final static native int viAssertIntrSignal(long jarg1, short jarg2, long jarg3);
  public final static native int viMapTrigger(long jarg1, short jarg2, short jarg3, int jarg4);
  public final static native int viUnmapTrigger(long jarg1, short jarg2, short jarg3);
  public final static native int viUsbControlOut(long jarg1, short jarg2, short jarg3, int jarg4, int jarg5, int jarg6, long jarg7);
  public final static native int viUsbControlIn(long jarg1, short jarg2, short jarg3, int jarg4, int jarg5, int jarg6, long jarg7, long jarg8);
  public final static native int viVxiServantResponse(long jarg1, short jarg2, long jarg3);
}
