/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static int viOpenDefaultRM(SWIGTYPE_p_unsigned_int vi) {
    return exampleJNI.viOpenDefaultRM(SWIGTYPE_p_unsigned_int.getCPtr(vi));
  }

  public static int viFindRsrc(long sesn, String expr, SWIGTYPE_p_unsigned_int vi, SWIGTYPE_p_unsigned_int retCnt, String desc) {
    return exampleJNI.viFindRsrc(sesn, expr, SWIGTYPE_p_unsigned_int.getCPtr(vi), SWIGTYPE_p_unsigned_int.getCPtr(retCnt), desc);
  }

  public static int viFindNext(long vi, String desc) {
    return exampleJNI.viFindNext(vi, desc);
  }

  public static int viParseRsrc(long rmSesn, String rsrcName, SWIGTYPE_p_unsigned_short intfType, SWIGTYPE_p_unsigned_short intfNum) {
    return exampleJNI.viParseRsrc(rmSesn, rsrcName, SWIGTYPE_p_unsigned_short.getCPtr(intfType), SWIGTYPE_p_unsigned_short.getCPtr(intfNum));
  }

  public static int viParseRsrcEx(long rmSesn, String rsrcName, SWIGTYPE_p_unsigned_short intfType, SWIGTYPE_p_unsigned_short intfNum, String rsrcClass, String expandedUnaliasedName, String aliasIfExists) {
    return exampleJNI.viParseRsrcEx(rmSesn, rsrcName, SWIGTYPE_p_unsigned_short.getCPtr(intfType), SWIGTYPE_p_unsigned_short.getCPtr(intfNum), rsrcClass, expandedUnaliasedName, aliasIfExists);
  }

  public static int viOpen(long sesn, String name, long mode, long timeout, SWIGTYPE_p_unsigned_int vi) {
    return exampleJNI.viOpen(sesn, name, mode, timeout, SWIGTYPE_p_unsigned_int.getCPtr(vi));
  }

  public static int viClose(long vi) {
    return exampleJNI.viClose(vi);
  }

  public static int viSetAttribute(long vi, long attrName, SWIGTYPE_p_u_int64_t attrValue) {
    return exampleJNI.viSetAttribute(vi, attrName, SWIGTYPE_p_u_int64_t.getCPtr(attrValue));
  }

  public static int viGetAttribute(long vi, long attrName, SWIGTYPE_p_void attrValue) {
    return exampleJNI.viGetAttribute(vi, attrName, SWIGTYPE_p_void.getCPtr(attrValue));
  }

  public static int viStatusDesc(long vi, int status, String desc) {
    return exampleJNI.viStatusDesc(vi, status, desc);
  }

  public static int viTerminate(long vi, int degree, long jobId) {
    return exampleJNI.viTerminate(vi, degree, jobId);
  }

  public static int viLock(long vi, long lockType, long timeout, String requestedKey, String accessKey) {
    return exampleJNI.viLock(vi, lockType, timeout, requestedKey, accessKey);
  }

  public static int viUnlock(long vi) {
    return exampleJNI.viUnlock(vi);
  }

  public static int viEnableEvent(long vi, long eventType, int mechanism, long context) {
    return exampleJNI.viEnableEvent(vi, eventType, mechanism, context);
  }

  public static int viDisableEvent(long vi, long eventType, int mechanism) {
    return exampleJNI.viDisableEvent(vi, eventType, mechanism);
  }

  public static int viDiscardEvents(long vi, long eventType, int mechanism) {
    return exampleJNI.viDiscardEvents(vi, eventType, mechanism);
  }

  public static int viWaitOnEvent(long vi, long inEventType, long timeout, SWIGTYPE_p_unsigned_int outEventType, SWIGTYPE_p_unsigned_int outContext) {
    return exampleJNI.viWaitOnEvent(vi, inEventType, timeout, SWIGTYPE_p_unsigned_int.getCPtr(outEventType), SWIGTYPE_p_unsigned_int.getCPtr(outContext));
  }

  public static int viInstallHandler(long vi, long eventType, SWIGTYPE_p_f_unsigned_int_unsigned_int_unsigned_int_p_void__int handler, SWIGTYPE_p_void userHandle) {
    return exampleJNI.viInstallHandler(vi, eventType, SWIGTYPE_p_f_unsigned_int_unsigned_int_unsigned_int_p_void__int.getCPtr(handler), SWIGTYPE_p_void.getCPtr(userHandle));
  }

  public static int viUninstallHandler(long vi, long eventType, SWIGTYPE_p_f_unsigned_int_unsigned_int_unsigned_int_p_void__int handler, SWIGTYPE_p_void userHandle) {
    return exampleJNI.viUninstallHandler(vi, eventType, SWIGTYPE_p_f_unsigned_int_unsigned_int_unsigned_int_p_void__int.getCPtr(handler), SWIGTYPE_p_void.getCPtr(userHandle));
  }

  public static int viRead(long vi, SWIGTYPE_p_unsigned_char buf, long cnt, SWIGTYPE_p_unsigned_int retCnt) {
    return exampleJNI.viRead(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), cnt, SWIGTYPE_p_unsigned_int.getCPtr(retCnt));
  }

  public static int viReadAsync(long vi, SWIGTYPE_p_unsigned_char buf, long cnt, SWIGTYPE_p_unsigned_int jobId) {
    return exampleJNI.viReadAsync(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), cnt, SWIGTYPE_p_unsigned_int.getCPtr(jobId));
  }

  public static int viReadToFile(long vi, String filename, long cnt, SWIGTYPE_p_unsigned_int retCnt) {
    return exampleJNI.viReadToFile(vi, filename, cnt, SWIGTYPE_p_unsigned_int.getCPtr(retCnt));
  }

  public static int viWrite(long vi, SWIGTYPE_p_unsigned_char buf, long cnt, SWIGTYPE_p_unsigned_int retCnt) {
    return exampleJNI.viWrite(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), cnt, SWIGTYPE_p_unsigned_int.getCPtr(retCnt));
  }

  public static int viWriteAsync(long vi, SWIGTYPE_p_unsigned_char buf, long cnt, SWIGTYPE_p_unsigned_int jobId) {
    return exampleJNI.viWriteAsync(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), cnt, SWIGTYPE_p_unsigned_int.getCPtr(jobId));
  }

  public static int viWriteFromFile(long vi, String filename, long cnt, SWIGTYPE_p_unsigned_int retCnt) {
    return exampleJNI.viWriteFromFile(vi, filename, cnt, SWIGTYPE_p_unsigned_int.getCPtr(retCnt));
  }

  public static int viAssertTrigger(long vi, int protocol) {
    return exampleJNI.viAssertTrigger(vi, protocol);
  }

  public static int viReadSTB(long vi, SWIGTYPE_p_unsigned_short status) {
    return exampleJNI.viReadSTB(vi, SWIGTYPE_p_unsigned_short.getCPtr(status));
  }

  public static int viClear(long vi) {
    return exampleJNI.viClear(vi);
  }

  public static int viSetBuf(long vi, int mask, long size) {
    return exampleJNI.viSetBuf(vi, mask, size);
  }

  public static int viFlush(long vi, int mask) {
    return exampleJNI.viFlush(vi, mask);
  }

  public static int viBufWrite(long vi, SWIGTYPE_p_unsigned_char buf, long cnt, SWIGTYPE_p_unsigned_int retCnt) {
    return exampleJNI.viBufWrite(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), cnt, SWIGTYPE_p_unsigned_int.getCPtr(retCnt));
  }

  public static int viBufRead(long vi, SWIGTYPE_p_unsigned_char buf, long cnt, SWIGTYPE_p_unsigned_int retCnt) {
    return exampleJNI.viBufRead(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), cnt, SWIGTYPE_p_unsigned_int.getCPtr(retCnt));
  }

  public static int viPrintf(long vi, String writeFmt) {
    return exampleJNI.viPrintf(vi, writeFmt);
  }

  public static int viSPrintf(long vi, SWIGTYPE_p_unsigned_char buf, String writeFmt) {
    return exampleJNI.viSPrintf(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), writeFmt);
  }

  public static int viScanf(long vi, String readFmt) {
    return exampleJNI.viScanf(vi, readFmt);
  }

  public static int viSScanf(long vi, SWIGTYPE_p_unsigned_char buf, String readFmt) {
    return exampleJNI.viSScanf(vi, SWIGTYPE_p_unsigned_char.getCPtr(buf), readFmt);
  }

  public static int viQueryf(long vi, String writeFmt, String readFmt) {
    return exampleJNI.viQueryf(vi, writeFmt, readFmt);
  }

  public static int viIn8(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_unsigned_char val8) {
    return exampleJNI.viIn8(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_unsigned_char.getCPtr(val8));
  }

  public static int viOut8(long vi, int space, SWIGTYPE_p_u_int64_t offset, short val8) {
    return exampleJNI.viOut8(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), val8);
  }

  public static int viIn16(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_unsigned_short val16) {
    return exampleJNI.viIn16(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_unsigned_short.getCPtr(val16));
  }

  public static int viOut16(long vi, int space, SWIGTYPE_p_u_int64_t offset, int val16) {
    return exampleJNI.viOut16(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), val16);
  }

  public static int viIn32(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_unsigned_int val32) {
    return exampleJNI.viIn32(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_unsigned_int.getCPtr(val32));
  }

  public static int viOut32(long vi, int space, SWIGTYPE_p_u_int64_t offset, long val32) {
    return exampleJNI.viOut32(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), val32);
  }

  public static int viIn64(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t val64) {
    return exampleJNI.viIn64(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(val64));
  }

  public static int viOut64(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t val64) {
    return exampleJNI.viOut64(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(val64));
  }

  public static int viIn8Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_unsigned_char val8) {
    return exampleJNI.viIn8Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_unsigned_char.getCPtr(val8));
  }

  public static int viOut8Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, short val8) {
    return exampleJNI.viOut8Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), val8);
  }

  public static int viIn16Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_unsigned_short val16) {
    return exampleJNI.viIn16Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_unsigned_short.getCPtr(val16));
  }

  public static int viOut16Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, int val16) {
    return exampleJNI.viOut16Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), val16);
  }

  public static int viIn32Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_unsigned_int val32) {
    return exampleJNI.viIn32Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_unsigned_int.getCPtr(val32));
  }

  public static int viOut32Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, long val32) {
    return exampleJNI.viOut32Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), val32);
  }

  public static int viIn64Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t val64) {
    return exampleJNI.viIn64Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(val64));
  }

  public static int viOut64Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t val64) {
    return exampleJNI.viOut64Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(val64));
  }

  public static int viMoveIn8(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_char buf8) {
    return exampleJNI.viMoveIn8(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_char.getCPtr(buf8));
  }

  public static int viMoveOut8(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_char buf8) {
    return exampleJNI.viMoveOut8(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_char.getCPtr(buf8));
  }

  public static int viMoveIn16(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_short buf16) {
    return exampleJNI.viMoveIn16(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_short.getCPtr(buf16));
  }

  public static int viMoveOut16(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_short buf16) {
    return exampleJNI.viMoveOut16(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_short.getCPtr(buf16));
  }

  public static int viMoveIn32(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_int buf32) {
    return exampleJNI.viMoveIn32(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_int.getCPtr(buf32));
  }

  public static int viMoveOut32(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_int buf32) {
    return exampleJNI.viMoveOut32(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_int.getCPtr(buf32));
  }

  public static int viMoveIn64(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_u_int64_t buf64) {
    return exampleJNI.viMoveIn64(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_u_int64_t.getCPtr(buf64));
  }

  public static int viMoveOut64(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_u_int64_t buf64) {
    return exampleJNI.viMoveOut64(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_u_int64_t.getCPtr(buf64));
  }

  public static int viMoveIn8Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_char buf8) {
    return exampleJNI.viMoveIn8Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_char.getCPtr(buf8));
  }

  public static int viMoveOut8Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_char buf8) {
    return exampleJNI.viMoveOut8Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_char.getCPtr(buf8));
  }

  public static int viMoveIn16Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_short buf16) {
    return exampleJNI.viMoveIn16Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_short.getCPtr(buf16));
  }

  public static int viMoveOut16Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_short buf16) {
    return exampleJNI.viMoveOut16Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_short.getCPtr(buf16));
  }

  public static int viMoveIn32Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_int buf32) {
    return exampleJNI.viMoveIn32Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_int.getCPtr(buf32));
  }

  public static int viMoveOut32Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_unsigned_int buf32) {
    return exampleJNI.viMoveOut32Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_unsigned_int.getCPtr(buf32));
  }

  public static int viMoveIn64Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_u_int64_t buf64) {
    return exampleJNI.viMoveIn64Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_u_int64_t.getCPtr(buf64));
  }

  public static int viMoveOut64Ex(long vi, int space, SWIGTYPE_p_u_int64_t offset, SWIGTYPE_p_u_int64_t length, SWIGTYPE_p_u_int64_t buf64) {
    return exampleJNI.viMoveOut64Ex(vi, space, SWIGTYPE_p_u_int64_t.getCPtr(offset), SWIGTYPE_p_u_int64_t.getCPtr(length), SWIGTYPE_p_u_int64_t.getCPtr(buf64));
  }

  public static int viMove(long vi, int srcSpace, SWIGTYPE_p_u_int64_t srcOffset, int srcWidth, int destSpace, SWIGTYPE_p_u_int64_t destOffset, int destWidth, SWIGTYPE_p_u_int64_t srcLength) {
    return exampleJNI.viMove(vi, srcSpace, SWIGTYPE_p_u_int64_t.getCPtr(srcOffset), srcWidth, destSpace, SWIGTYPE_p_u_int64_t.getCPtr(destOffset), destWidth, SWIGTYPE_p_u_int64_t.getCPtr(srcLength));
  }

  public static int viMoveAsync(long vi, int srcSpace, SWIGTYPE_p_u_int64_t srcOffset, int srcWidth, int destSpace, SWIGTYPE_p_u_int64_t destOffset, int destWidth, SWIGTYPE_p_u_int64_t srcLength, SWIGTYPE_p_unsigned_int jobId) {
    return exampleJNI.viMoveAsync(vi, srcSpace, SWIGTYPE_p_u_int64_t.getCPtr(srcOffset), srcWidth, destSpace, SWIGTYPE_p_u_int64_t.getCPtr(destOffset), destWidth, SWIGTYPE_p_u_int64_t.getCPtr(srcLength), SWIGTYPE_p_unsigned_int.getCPtr(jobId));
  }

  public static int viMoveEx(long vi, int srcSpace, SWIGTYPE_p_u_int64_t srcOffset, int srcWidth, int destSpace, SWIGTYPE_p_u_int64_t destOffset, int destWidth, SWIGTYPE_p_u_int64_t srcLength) {
    return exampleJNI.viMoveEx(vi, srcSpace, SWIGTYPE_p_u_int64_t.getCPtr(srcOffset), srcWidth, destSpace, SWIGTYPE_p_u_int64_t.getCPtr(destOffset), destWidth, SWIGTYPE_p_u_int64_t.getCPtr(srcLength));
  }

  public static int viMoveAsyncEx(long vi, int srcSpace, SWIGTYPE_p_u_int64_t srcOffset, int srcWidth, int destSpace, SWIGTYPE_p_u_int64_t destOffset, int destWidth, SWIGTYPE_p_u_int64_t srcLength, SWIGTYPE_p_unsigned_int jobId) {
    return exampleJNI.viMoveAsyncEx(vi, srcSpace, SWIGTYPE_p_u_int64_t.getCPtr(srcOffset), srcWidth, destSpace, SWIGTYPE_p_u_int64_t.getCPtr(destOffset), destWidth, SWIGTYPE_p_u_int64_t.getCPtr(srcLength), SWIGTYPE_p_unsigned_int.getCPtr(jobId));
  }

  public static int viMapAddress(long vi, int mapSpace, SWIGTYPE_p_u_int64_t mapOffset, SWIGTYPE_p_u_int64_t mapSize, int access, SWIGTYPE_p_void suggested, SWIGTYPE_p_p_void address) {
    return exampleJNI.viMapAddress(vi, mapSpace, SWIGTYPE_p_u_int64_t.getCPtr(mapOffset), SWIGTYPE_p_u_int64_t.getCPtr(mapSize), access, SWIGTYPE_p_void.getCPtr(suggested), SWIGTYPE_p_p_void.getCPtr(address));
  }

  public static int viUnmapAddress(long vi) {
    return exampleJNI.viUnmapAddress(vi);
  }

  public static int viMapAddressEx(long vi, int mapSpace, SWIGTYPE_p_u_int64_t mapOffset, SWIGTYPE_p_u_int64_t mapSize, int access, SWIGTYPE_p_void suggested, SWIGTYPE_p_p_void address) {
    return exampleJNI.viMapAddressEx(vi, mapSpace, SWIGTYPE_p_u_int64_t.getCPtr(mapOffset), SWIGTYPE_p_u_int64_t.getCPtr(mapSize), access, SWIGTYPE_p_void.getCPtr(suggested), SWIGTYPE_p_p_void.getCPtr(address));
  }

  public static void viPeek8(long vi, SWIGTYPE_p_void address, SWIGTYPE_p_unsigned_char val8) {
    exampleJNI.viPeek8(vi, SWIGTYPE_p_void.getCPtr(address), SWIGTYPE_p_unsigned_char.getCPtr(val8));
  }

  public static void viPoke8(long vi, SWIGTYPE_p_void address, short val8) {
    exampleJNI.viPoke8(vi, SWIGTYPE_p_void.getCPtr(address), val8);
  }

  public static void viPeek16(long vi, SWIGTYPE_p_void address, SWIGTYPE_p_unsigned_short val16) {
    exampleJNI.viPeek16(vi, SWIGTYPE_p_void.getCPtr(address), SWIGTYPE_p_unsigned_short.getCPtr(val16));
  }

  public static void viPoke16(long vi, SWIGTYPE_p_void address, int val16) {
    exampleJNI.viPoke16(vi, SWIGTYPE_p_void.getCPtr(address), val16);
  }

  public static void viPeek32(long vi, SWIGTYPE_p_void address, SWIGTYPE_p_unsigned_int val32) {
    exampleJNI.viPeek32(vi, SWIGTYPE_p_void.getCPtr(address), SWIGTYPE_p_unsigned_int.getCPtr(val32));
  }

  public static void viPoke32(long vi, SWIGTYPE_p_void address, long val32) {
    exampleJNI.viPoke32(vi, SWIGTYPE_p_void.getCPtr(address), val32);
  }

  public static void viPeek64(long vi, SWIGTYPE_p_void address, SWIGTYPE_p_u_int64_t val64) {
    exampleJNI.viPeek64(vi, SWIGTYPE_p_void.getCPtr(address), SWIGTYPE_p_u_int64_t.getCPtr(val64));
  }

  public static void viPoke64(long vi, SWIGTYPE_p_void address, SWIGTYPE_p_u_int64_t val64) {
    exampleJNI.viPoke64(vi, SWIGTYPE_p_void.getCPtr(address), SWIGTYPE_p_u_int64_t.getCPtr(val64));
  }

  public static int viMemAlloc(long vi, SWIGTYPE_p_u_int64_t size, SWIGTYPE_p_u_int64_t offset) {
    return exampleJNI.viMemAlloc(vi, SWIGTYPE_p_u_int64_t.getCPtr(size), SWIGTYPE_p_u_int64_t.getCPtr(offset));
  }

  public static int viMemFree(long vi, SWIGTYPE_p_u_int64_t offset) {
    return exampleJNI.viMemFree(vi, SWIGTYPE_p_u_int64_t.getCPtr(offset));
  }

  public static int viMemAllocEx(long vi, SWIGTYPE_p_u_int64_t size, SWIGTYPE_p_u_int64_t offset) {
    return exampleJNI.viMemAllocEx(vi, SWIGTYPE_p_u_int64_t.getCPtr(size), SWIGTYPE_p_u_int64_t.getCPtr(offset));
  }

  public static int viMemFreeEx(long vi, SWIGTYPE_p_u_int64_t offset) {
    return exampleJNI.viMemFreeEx(vi, SWIGTYPE_p_u_int64_t.getCPtr(offset));
  }

  public static int viGpibControlREN(long vi, int mode) {
    return exampleJNI.viGpibControlREN(vi, mode);
  }

  public static int viGpibControlATN(long vi, int mode) {
    return exampleJNI.viGpibControlATN(vi, mode);
  }

  public static int viGpibSendIFC(long vi) {
    return exampleJNI.viGpibSendIFC(vi);
  }

  public static int viGpibCommand(long vi, SWIGTYPE_p_unsigned_char cmd, long cnt, SWIGTYPE_p_unsigned_int retCnt) {
    return exampleJNI.viGpibCommand(vi, SWIGTYPE_p_unsigned_char.getCPtr(cmd), cnt, SWIGTYPE_p_unsigned_int.getCPtr(retCnt));
  }

  public static int viGpibPassControl(long vi, int primAddr, int secAddr) {
    return exampleJNI.viGpibPassControl(vi, primAddr, secAddr);
  }

  public static int viVxiCommandQuery(long vi, int mode, long cmd, SWIGTYPE_p_unsigned_int response) {
    return exampleJNI.viVxiCommandQuery(vi, mode, cmd, SWIGTYPE_p_unsigned_int.getCPtr(response));
  }

  public static int viAssertUtilSignal(long vi, int line) {
    return exampleJNI.viAssertUtilSignal(vi, line);
  }

  public static int viAssertIntrSignal(long vi, short mode, long statusID) {
    return exampleJNI.viAssertIntrSignal(vi, mode, statusID);
  }

  public static int viMapTrigger(long vi, short trigSrc, short trigDest, int mode) {
    return exampleJNI.viMapTrigger(vi, trigSrc, trigDest, mode);
  }

  public static int viUnmapTrigger(long vi, short trigSrc, short trigDest) {
    return exampleJNI.viUnmapTrigger(vi, trigSrc, trigDest);
  }

  public static int viUsbControlOut(long vi, short bmRequestType, short bRequest, int wValue, int wIndex, int wLength, SWIGTYPE_p_unsigned_char buf) {
    return exampleJNI.viUsbControlOut(vi, bmRequestType, bRequest, wValue, wIndex, wLength, SWIGTYPE_p_unsigned_char.getCPtr(buf));
  }

  public static int viUsbControlIn(long vi, short bmRequestType, short bRequest, int wValue, int wIndex, int wLength, SWIGTYPE_p_unsigned_char buf, SWIGTYPE_p_unsigned_short retCnt) {
    return exampleJNI.viUsbControlIn(vi, bmRequestType, bRequest, wValue, wIndex, wLength, SWIGTYPE_p_unsigned_char.getCPtr(buf), SWIGTYPE_p_unsigned_short.getCPtr(retCnt));
  }

  public static int viVxiServantResponse(long vi, short mode, long resp) {
    return exampleJNI.viVxiServantResponse(vi, mode, resp);
  }

}
