/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "visapre.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_exampleJNI_viOpenDefaultRM(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  ViPSession arg1 = (ViPSession) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ViPSession *)&jarg1; 
  result = (ViStatus)viOpenDefaultRM(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viFindRsrc(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4, jstring jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViString arg2 = (ViString) 0 ;
  ViPFindList arg3 = (ViPFindList) 0 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViChar *arg5 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViString)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(ViPFindList *)&jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  result = (ViStatus)viFindRsrc(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viFindNext(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  ViFindList arg1 ;
  ViChar *arg2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViFindList)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (ViStatus)viFindNext(arg1,arg2);
  jresult = (jint)result; 
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viParseRsrc(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViRsrc arg2 = (ViRsrc) 0 ;
  ViPUInt16 arg3 = (ViPUInt16) 0 ;
  ViPUInt16 arg4 = (ViPUInt16) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViRsrc)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(ViPUInt16 *)&jarg3; 
  arg4 = *(ViPUInt16 *)&jarg4; 
  result = (ViStatus)viParseRsrc(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viParseRsrcEx(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4, jstring jarg5, jstring jarg6, jstring jarg7) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViRsrc arg2 = (ViRsrc) 0 ;
  ViPUInt16 arg3 = (ViPUInt16) 0 ;
  ViPUInt16 arg4 = (ViPUInt16) 0 ;
  ViChar *arg5 ;
  ViChar *arg6 ;
  ViChar *arg7 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViRsrc)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(ViPUInt16 *)&jarg3; 
  arg4 = *(ViPUInt16 *)&jarg4; 
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  arg6 = 0;
  if (jarg6) {
    arg6 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0);
    if (!arg6) return 0;
  }
  arg7 = 0;
  if (jarg7) {
    arg7 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg7, 0);
    if (!arg7) return 0;
  }
  result = (ViStatus)viParseRsrcEx(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  
  
  
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
  if (arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, (const char *)arg6);
  if (arg7) (*jenv)->ReleaseStringUTFChars(jenv, jarg7, (const char *)arg7);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOpen(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViRsrc arg2 = (ViRsrc) 0 ;
  ViAccessMode arg3 ;
  ViUInt32 arg4 ;
  ViPSession arg5 = (ViPSession) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViRsrc)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (ViAccessMode)jarg3; 
  arg4 = (ViUInt32)jarg4; 
  arg5 = *(ViPSession *)&jarg5; 
  result = (ViStatus)viOpen(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viClose(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  ViObject arg1 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViObject)jarg1; 
  result = (ViStatus)viClose(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viSetAttribute(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViObject arg1 ;
  ViAttr arg2 ;
  ViAttrState arg3 ;
  ViAttrState *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViObject)jarg1; 
  arg2 = (ViAttr)jarg2; 
  argp3 = *(ViAttrState **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViAttrState");
    return 0;
  }
  arg3 = *argp3; 
  result = (ViStatus)viSetAttribute(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viGetAttribute(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViObject arg1 ;
  ViAttr arg2 ;
  void *arg3 = (void *) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViObject)jarg1; 
  arg2 = (ViAttr)jarg2; 
  arg3 = *(void **)&jarg3; 
  result = (ViStatus)viGetAttribute(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viStatusDesc(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3) {
  jint jresult = 0 ;
  ViObject arg1 ;
  ViStatus arg2 ;
  ViChar *arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViObject)jarg1; 
  arg2 = (ViStatus)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (ViStatus)viStatusDesc(arg1,arg2,arg3);
  jresult = (jint)result; 
  
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viTerminate(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViObject arg1 ;
  ViUInt16 arg2 ;
  ViJobId arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViObject)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  arg3 = (ViJobId)jarg3; 
  result = (ViStatus)viTerminate(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viLock(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jstring jarg4, jstring jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViAccessMode arg2 ;
  ViUInt32 arg3 ;
  ViKeyId arg4 = (ViKeyId) 0 ;
  ViChar *arg5 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViAccessMode)jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (ViKeyId)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  result = (ViStatus)viLock(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viUnlock(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  result = (ViStatus)viUnlock(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viEnableEvent(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViEventType arg2 ;
  ViUInt16 arg3 ;
  ViEventFilter arg4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViEventType)jarg2; 
  arg3 = (ViUInt16)jarg3; 
  arg4 = (ViEventFilter)jarg4; 
  result = (ViStatus)viEnableEvent(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viDisableEvent(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViEventType arg2 ;
  ViUInt16 arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViEventType)jarg2; 
  arg3 = (ViUInt16)jarg3; 
  result = (ViStatus)viDisableEvent(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viDiscardEvents(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViEventType arg2 ;
  ViUInt16 arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViEventType)jarg2; 
  arg3 = (ViUInt16)jarg3; 
  result = (ViStatus)viDiscardEvents(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viWaitOnEvent(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViEventType arg2 ;
  ViUInt32 arg3 ;
  ViPEventType arg4 = (ViPEventType) 0 ;
  ViPEvent arg5 = (ViPEvent) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViEventType)jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPEventType *)&jarg4; 
  arg5 = *(ViPEvent *)&jarg5; 
  result = (ViStatus)viWaitOnEvent(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viInstallHandler(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViEventType arg2 ;
  ViHndlr arg3 = (ViHndlr) 0 ;
  ViAddr arg4 = (ViAddr) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViEventType)jarg2; 
  arg3 = *(ViHndlr *)&jarg3; 
  arg4 = *(ViAddr *)&jarg4; 
  result = (ViStatus)viInstallHandler(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viUninstallHandler(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViEventType arg2 ;
  ViHndlr arg3 = (ViHndlr) 0 ;
  ViAddr arg4 = (ViAddr) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViEventType)jarg2; 
  arg3 = *(ViHndlr *)&jarg3; 
  arg4 = *(ViAddr *)&jarg4; 
  result = (ViStatus)viUninstallHandler(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viRead(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViPBuf arg2 = (ViPBuf) 0 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViPBuf *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viRead(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viReadAsync(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViPBuf arg2 = (ViPBuf) 0 ;
  ViUInt32 arg3 ;
  ViPJobId arg4 = (ViPJobId) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViPBuf *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPJobId *)&jarg4; 
  result = (ViStatus)viReadAsync(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viReadToFile(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViConstString arg2 = (ViConstString) 0 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViConstString)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viReadToFile(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viWrite(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBuf arg2 = (ViBuf) 0 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViBuf *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viWrite(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viWriteAsync(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBuf arg2 = (ViBuf) 0 ;
  ViUInt32 arg3 ;
  ViPJobId arg4 = (ViPJobId) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViBuf *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPJobId *)&jarg4; 
  result = (ViStatus)viWriteAsync(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viWriteFromFile(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViConstString arg2 = (ViConstString) 0 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViConstString)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viWriteFromFile(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viAssertTrigger(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  result = (ViStatus)viAssertTrigger(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viReadSTB(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViPUInt16 arg2 = (ViPUInt16) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViPUInt16 *)&jarg2; 
  result = (ViStatus)viReadSTB(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viClear(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  result = (ViStatus)viClear(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viSetBuf(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViUInt32 arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  arg3 = (ViUInt32)jarg3; 
  result = (ViStatus)viSetBuf(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viFlush(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  result = (ViStatus)viFlush(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viBufWrite(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBuf arg2 = (ViBuf) 0 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViBuf *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viBufWrite(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viBufRead(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViPBuf arg2 = (ViPBuf) 0 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViPBuf *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viBufRead(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viPrintf(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViString arg2 = (ViString) 0 ;
  void *arg3 = 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViString)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (ViStatus)viPrintf(arg1,arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viSPrintf(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViPBuf arg2 = (ViPBuf) 0 ;
  ViString arg3 = (ViString) 0 ;
  void *arg4 = 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViPBuf *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (ViString)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (ViStatus)viSPrintf(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viScanf(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViString arg2 = (ViString) 0 ;
  void *arg3 = 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViString)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (ViStatus)viScanf(arg1,arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viSScanf(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBuf arg2 = (ViBuf) 0 ;
  ViString arg3 = (ViString) 0 ;
  void *arg4 = 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViBuf *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (ViString)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (ViStatus)viSScanf(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viQueryf(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViString arg2 = (ViString) 0 ;
  ViString arg3 = (ViString) 0 ;
  void *arg4 = 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (ViString)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (ViString)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (ViStatus)viQueryf(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn8(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViPUInt8 arg4 = (ViPUInt8) 0 ;
  ViBusAddress *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt8 *)&jarg4; 
  result = (ViStatus)viIn8(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut8(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jshort jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViUInt8 arg4 ;
  ViBusAddress *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt8)jarg4; 
  result = (ViStatus)viOut8(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn16(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViPUInt16 arg4 = (ViPUInt16) 0 ;
  ViBusAddress *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt16 *)&jarg4; 
  result = (ViStatus)viIn16(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut16(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViUInt16 arg4 ;
  ViBusAddress *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt16)jarg4; 
  result = (ViStatus)viOut16(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn32(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViBusAddress *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viIn32(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut32(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViUInt32 arg4 ;
  ViBusAddress *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt32)jarg4; 
  result = (ViStatus)viOut32(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn64(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViPUInt64 arg4 = (ViPUInt64) 0 ;
  ViBusAddress *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt64 *)&jarg4; 
  result = (ViStatus)viIn64(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut64(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViUInt64 arg4 ;
  ViBusAddress *argp3 ;
  ViUInt64 *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViUInt64 **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViUInt64");
    return 0;
  }
  arg4 = *argp4; 
  result = (ViStatus)viOut64(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn8Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViPUInt8 arg4 = (ViPUInt8) 0 ;
  ViBusAddress64 *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt8 *)&jarg4; 
  result = (ViStatus)viIn8Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut8Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jshort jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViUInt8 arg4 ;
  ViBusAddress64 *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt8)jarg4; 
  result = (ViStatus)viOut8Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn16Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViPUInt16 arg4 = (ViPUInt16) 0 ;
  ViBusAddress64 *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt16 *)&jarg4; 
  result = (ViStatus)viIn16Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut16Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViUInt16 arg4 ;
  ViBusAddress64 *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt16)jarg4; 
  result = (ViStatus)viOut16Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn32Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViBusAddress64 *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viIn32Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut32Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViUInt32 arg4 ;
  ViBusAddress64 *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt32)jarg4; 
  result = (ViStatus)viOut32Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viIn64Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViPUInt64 arg4 = (ViPUInt64) 0 ;
  ViBusAddress64 *argp3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(ViPUInt64 *)&jarg4; 
  result = (ViStatus)viIn64Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viOut64Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViUInt64 arg4 ;
  ViBusAddress64 *argp3 ;
  ViUInt64 *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViUInt64 **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViUInt64");
    return 0;
  }
  arg4 = *argp4; 
  result = (ViStatus)viOut64Ex(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn8(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt8 arg5 = (ViAUInt8) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt8 *)&jarg5; 
  result = (ViStatus)viMoveIn8(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut8(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt8 arg5 = (ViAUInt8) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt8 *)&jarg5; 
  result = (ViStatus)viMoveOut8(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn16(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt16 arg5 = (ViAUInt16) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt16 *)&jarg5; 
  result = (ViStatus)viMoveIn16(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut16(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt16 arg5 = (ViAUInt16) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt16 *)&jarg5; 
  result = (ViStatus)viMoveOut16(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn32(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt32 arg5 = (ViAUInt32) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt32 *)&jarg5; 
  result = (ViStatus)viMoveIn32(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut32(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt32 arg5 = (ViAUInt32) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt32 *)&jarg5; 
  result = (ViStatus)viMoveOut32(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn64(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt64 arg5 = (ViAUInt64) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt64 *)&jarg5; 
  result = (ViStatus)viMoveIn64(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut64(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViAUInt64 arg5 = (ViAUInt64) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt64 *)&jarg5; 
  result = (ViStatus)viMoveOut64(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn8Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt8 arg5 = (ViAUInt8) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt8 *)&jarg5; 
  result = (ViStatus)viMoveIn8Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut8Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt8 arg5 = (ViAUInt8) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt8 *)&jarg5; 
  result = (ViStatus)viMoveOut8Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn16Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt16 arg5 = (ViAUInt16) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt16 *)&jarg5; 
  result = (ViStatus)viMoveIn16Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut16Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt16 arg5 = (ViAUInt16) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt16 *)&jarg5; 
  result = (ViStatus)viMoveOut16Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn32Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt32 arg5 = (ViAUInt32) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt32 *)&jarg5; 
  result = (ViStatus)viMoveIn32Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut32Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt32 arg5 = (ViAUInt32) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt32 *)&jarg5; 
  result = (ViStatus)viMoveOut32Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveIn64Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt64 arg5 = (ViAUInt64) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt64 *)&jarg5; 
  result = (ViStatus)viMoveIn64Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveOut64Ex(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViAUInt64 arg5 = (ViAUInt64) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(ViAUInt64 *)&jarg5; 
  result = (ViStatus)viMoveOut64Ex(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMove(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4, jint jarg5, jlong jarg6, jint jarg7, jlong jarg8) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViUInt16 arg4 ;
  ViUInt16 arg5 ;
  ViBusAddress arg6 ;
  ViUInt16 arg7 ;
  ViBusSize arg8 ;
  ViBusAddress *argp3 ;
  ViBusAddress *argp6 ;
  ViBusSize *argp8 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt16)jarg4; 
  arg5 = (ViUInt16)jarg5; 
  argp6 = *(ViBusAddress **)&jarg6; 
  if (!argp6) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg6 = *argp6; 
  arg7 = (ViUInt16)jarg7; 
  argp8 = *(ViBusSize **)&jarg8; 
  if (!argp8) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg8 = *argp8; 
  result = (ViStatus)viMove(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveAsync(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4, jint jarg5, jlong jarg6, jint jarg7, jlong jarg8, jlong jarg9) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViUInt16 arg4 ;
  ViUInt16 arg5 ;
  ViBusAddress arg6 ;
  ViUInt16 arg7 ;
  ViBusSize arg8 ;
  ViPJobId arg9 = (ViPJobId) 0 ;
  ViBusAddress *argp3 ;
  ViBusAddress *argp6 ;
  ViBusSize *argp8 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt16)jarg4; 
  arg5 = (ViUInt16)jarg5; 
  argp6 = *(ViBusAddress **)&jarg6; 
  if (!argp6) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg6 = *argp6; 
  arg7 = (ViUInt16)jarg7; 
  argp8 = *(ViBusSize **)&jarg8; 
  if (!argp8) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg8 = *argp8; 
  arg9 = *(ViPJobId *)&jarg9; 
  result = (ViStatus)viMoveAsync(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveEx(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4, jint jarg5, jlong jarg6, jint jarg7, jlong jarg8) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViUInt16 arg4 ;
  ViUInt16 arg5 ;
  ViBusAddress64 arg6 ;
  ViUInt16 arg7 ;
  ViBusSize arg8 ;
  ViBusAddress64 *argp3 ;
  ViBusAddress64 *argp6 ;
  ViBusSize *argp8 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt16)jarg4; 
  arg5 = (ViUInt16)jarg5; 
  argp6 = *(ViBusAddress64 **)&jarg6; 
  if (!argp6) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg6 = *argp6; 
  arg7 = (ViUInt16)jarg7; 
  argp8 = *(ViBusSize **)&jarg8; 
  if (!argp8) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg8 = *argp8; 
  result = (ViStatus)viMoveEx(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMoveAsyncEx(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4, jint jarg5, jlong jarg6, jint jarg7, jlong jarg8, jlong jarg9) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViUInt16 arg4 ;
  ViUInt16 arg5 ;
  ViBusAddress64 arg6 ;
  ViUInt16 arg7 ;
  ViBusSize arg8 ;
  ViPJobId arg9 = (ViPJobId) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusAddress64 *argp6 ;
  ViBusSize *argp8 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (ViUInt16)jarg4; 
  arg5 = (ViUInt16)jarg5; 
  argp6 = *(ViBusAddress64 **)&jarg6; 
  if (!argp6) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg6 = *argp6; 
  arg7 = (ViUInt16)jarg7; 
  argp8 = *(ViBusSize **)&jarg8; 
  if (!argp8) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg8 = *argp8; 
  arg9 = *(ViPJobId *)&jarg9; 
  result = (ViStatus)viMoveAsyncEx(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMapAddress(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress arg3 ;
  ViBusSize arg4 ;
  ViBoolean arg5 ;
  ViAddr arg6 = (ViAddr) 0 ;
  ViPAddr arg7 = (ViPAddr) 0 ;
  ViBusAddress *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (ViBoolean)jarg5; 
  arg6 = *(ViAddr *)&jarg6; 
  arg7 = *(ViPAddr *)&jarg7; 
  result = (ViStatus)viMapAddress(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viUnmapAddress(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  result = (ViStatus)viUnmapAddress(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMapAddressEx(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViBusAddress64 arg3 ;
  ViBusSize arg4 ;
  ViBoolean arg5 ;
  ViAddr arg6 = (ViAddr) 0 ;
  ViPAddr arg7 = (ViPAddr) 0 ;
  ViBusAddress64 *argp3 ;
  ViBusSize *argp4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  argp3 = *(ViBusAddress64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(ViBusSize **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = (ViBoolean)jarg5; 
  arg6 = *(ViAddr *)&jarg6; 
  arg7 = *(ViPAddr *)&jarg7; 
  result = (ViStatus)viMapAddressEx(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPeek8(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViPUInt8 arg3 = (ViPUInt8) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  arg3 = *(ViPUInt8 *)&jarg3; 
  viPeek8(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPoke8(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jshort jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViUInt8 arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  arg3 = (ViUInt8)jarg3; 
  viPoke8(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPeek16(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViPUInt16 arg3 = (ViPUInt16) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  arg3 = *(ViPUInt16 *)&jarg3; 
  viPeek16(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPoke16(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViUInt16 arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  arg3 = (ViUInt16)jarg3; 
  viPoke16(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPeek32(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViPUInt32 arg3 = (ViPUInt32) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  arg3 = *(ViPUInt32 *)&jarg3; 
  viPeek32(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPoke32(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViUInt32 arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  viPoke32(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPeek64(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViPUInt64 arg3 = (ViPUInt64) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  arg3 = *(ViPUInt64 *)&jarg3; 
  viPeek64(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_exampleJNI_viPoke64(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  ViSession arg1 ;
  ViAddr arg2 = (ViAddr) 0 ;
  ViUInt64 arg3 ;
  ViUInt64 *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViAddr *)&jarg2; 
  argp3 = *(ViUInt64 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViUInt64");
    return ;
  }
  arg3 = *argp3; 
  viPoke64(arg1,arg2,arg3);
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMemAlloc(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBusSize arg2 ;
  ViPBusAddress arg3 = (ViPBusAddress) 0 ;
  ViBusSize *argp2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  argp2 = *(ViBusSize **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(ViPBusAddress *)&jarg3; 
  result = (ViStatus)viMemAlloc(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMemFree(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBusAddress arg2 ;
  ViBusAddress *argp2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  argp2 = *(ViBusAddress **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress");
    return 0;
  }
  arg2 = *argp2; 
  result = (ViStatus)viMemFree(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMemAllocEx(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBusSize arg2 ;
  ViPBusAddress64 arg3 = (ViPBusAddress64) 0 ;
  ViBusSize *argp2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  argp2 = *(ViBusSize **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusSize");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(ViPBusAddress64 *)&jarg3; 
  result = (ViStatus)viMemAllocEx(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMemFreeEx(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBusAddress64 arg2 ;
  ViBusAddress64 *argp2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  argp2 = *(ViBusAddress64 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ViBusAddress64");
    return 0;
  }
  arg2 = *argp2; 
  result = (ViStatus)viMemFreeEx(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viGpibControlREN(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  result = (ViStatus)viGpibControlREN(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viGpibControlATN(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  result = (ViStatus)viGpibControlATN(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viGpibSendIFC(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  result = (ViStatus)viGpibSendIFC(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viGpibCommand(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViBuf arg2 = (ViBuf) 0 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = *(ViBuf *)&jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viGpibCommand(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viGpibPassControl(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViUInt16 arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  arg3 = (ViUInt16)jarg3; 
  result = (ViStatus)viGpibPassControl(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viVxiCommandQuery(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViUInt32 arg3 ;
  ViPUInt32 arg4 = (ViPUInt32) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  arg3 = (ViUInt32)jarg3; 
  arg4 = *(ViPUInt32 *)&jarg4; 
  result = (ViStatus)viVxiCommandQuery(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viAssertUtilSignal(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViUInt16 arg2 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViUInt16)jarg2; 
  result = (ViStatus)viAssertUtilSignal(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viAssertIntrSignal(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViInt16 arg2 ;
  ViUInt32 arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViInt16)jarg2; 
  arg3 = (ViUInt32)jarg3; 
  result = (ViStatus)viAssertIntrSignal(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viMapTrigger(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jshort jarg3, jint jarg4) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViInt16 arg2 ;
  ViInt16 arg3 ;
  ViUInt16 arg4 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViInt16)jarg2; 
  arg3 = (ViInt16)jarg3; 
  arg4 = (ViUInt16)jarg4; 
  result = (ViStatus)viMapTrigger(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viUnmapTrigger(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jshort jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViInt16 arg2 ;
  ViInt16 arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViInt16)jarg2; 
  arg3 = (ViInt16)jarg3; 
  result = (ViStatus)viUnmapTrigger(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viUsbControlOut(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jshort jarg3, jint jarg4, jint jarg5, jint jarg6, jlong jarg7) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViInt16 arg2 ;
  ViInt16 arg3 ;
  ViUInt16 arg4 ;
  ViUInt16 arg5 ;
  ViUInt16 arg6 ;
  ViBuf arg7 = (ViBuf) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViInt16)jarg2; 
  arg3 = (ViInt16)jarg3; 
  arg4 = (ViUInt16)jarg4; 
  arg5 = (ViUInt16)jarg5; 
  arg6 = (ViUInt16)jarg6; 
  arg7 = *(ViBuf *)&jarg7; 
  result = (ViStatus)viUsbControlOut(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viUsbControlIn(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jshort jarg3, jint jarg4, jint jarg5, jint jarg6, jlong jarg7, jlong jarg8) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViInt16 arg2 ;
  ViInt16 arg3 ;
  ViUInt16 arg4 ;
  ViUInt16 arg5 ;
  ViUInt16 arg6 ;
  ViPBuf arg7 = (ViPBuf) 0 ;
  ViPUInt16 arg8 = (ViPUInt16) 0 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViInt16)jarg2; 
  arg3 = (ViInt16)jarg3; 
  arg4 = (ViUInt16)jarg4; 
  arg5 = (ViUInt16)jarg5; 
  arg6 = (ViUInt16)jarg6; 
  arg7 = *(ViPBuf *)&jarg7; 
  arg8 = *(ViPUInt16 *)&jarg8; 
  result = (ViStatus)viUsbControlIn(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_viVxiServantResponse(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jlong jarg3) {
  jint jresult = 0 ;
  ViSession arg1 ;
  ViInt16 arg2 ;
  ViUInt32 arg3 ;
  ViStatus result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (ViSession)jarg1; 
  arg2 = (ViInt16)jarg2; 
  arg3 = (ViUInt32)jarg3; 
  result = (ViStatus)viVxiServantResponse(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

